version: '3'
services:
  colormap:
    image: nginx:alpine
    container_name: colormap
    ports:
      - 80:80
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
