# .github/workflows/pull_request.yaml
name: Pull Request Checks

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened] # triggers on PR create, update, reopen
  workflow_dispatch: {} # allow manual execution

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 #

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check for node_modules cache
        id: node_modules-cache-check
        uses: actions/cache@v4
        with:
          # path to playwright install dir
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.node_modules-cache-check.cache-hit != 'true'
        run: npm ci

      - name: Check for Playwright cache
        id: playwright-cache-check
        uses: actions/cache@v4
        with:
          # path to playwright install dir
          path: ~/.cache/ms-playwright # https://www.cuketest.com/playwright/docs/browsers/
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright Dependencies
        # should always run as deps are needed to even use browser cache and should not be cached themselves
        run: npx playwright install-deps

      - name: Install Playwright Browsers (for Vitest Browser Mode or E2E)
        # should only run on cache miss
        run: npx playwright install --with-deps chromium firefox webkit
        if: steps.playwright-cache-check.outputs.cache-hit != 'true'

      - name: Run Lint and Check Formatting
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test:unit:run

      - name: Build Project
        run: npm run build

      - name: Start Server and Run E2E Tests
        run: npx start-server-and-test preview http://localhost:4173 'npm run test:e2e'
